app:
  port: 3000
  globalPrefix: api
  NODE_ENV: development

logger:
  trackingIdHeader: x-tenant-id

database:
  user: postgres
  password: postgres
  host: localhost
  port: 5438
  name: aiofc_db
  pool:
    max: 20
    min: 2
    idle_timeout: 30
    connect_timeout: 30
    max_lifetime: 1800 # 30分钟

tenant:
  isolationStrategy: database
  databaseIsolation: true
  schemaIsolation: false
  schemaHeader: x-tenant-schema
  databaseHeader: x-tenant-database

middleware:
  excludedPaths: # 中间件排除路径
    - /
    - /api
    - /health
    - /docs
    - /swagger
    - /tenants
